### ISSUE TITLE
Repository issue with DUBStepR

### ISSUE THREAD

**Issue by JSegueni** [bbbranjan/DUBStepR#2]
Hi,

I'm trying to use the findElbow() function.
However, it is not present in the DUBStepR R package.

I have tried installing DUBStepR using :  
remotes::install_github("bbbranjan/DUBStepR")
devtools::install_github("prabhakarlab/DUBStepR")
and using the CRAN installer: install.packages("DUBStepR").

I always get the same result with a package containing only the DUBStepR function and not any of the other functions.

Do you know why I have this issue ?

Best,
Mas.

**Comment by bbbranjan** [comment]
Thank you for raising this issue, @mas-dot. Unfortunately, for simplicity of use, we have not exported any of the supporting functions within DUBStepR. If you would like to use only the findElbow() function, please clone the entire git repository to your local directory, and run `source("<your-local-directory>/DUBStepR/R/findElbow.R")`. 

Apologies for the inconvenience.
